src/objects/Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone_Task__c.object
<CustomObject>
    <fields>
        <fullName>Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Milestone</label>
        <referenceTo>Milestone__c</referenceTo>
        <relationshipLabel>Milestone Tasks</relationshipLabel>
        <relationshipName>Milestone_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Milestone Tasks</relationshipLabel>
        <relationshipName>Milestone_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestone Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LoadingTestData.cls
@IsTest
public class LoadingTestData {

    @TestSetup
    static void setupTestData() {
        Test.loadData(Account.sObjectType, 'TestData_Accounts');
        Test.loadData(Project__c.sObjectType, 'TestData_Projects');
        Test.loadData(Milestone__c.sObjectType, 'TestData_Milestones');
        Test.loadData(Milestone_Task__c.sObjectType, 'TestData_MilestoneTasks');
    }
    
    @isTest
    static void shouldLoadTestData() {
        // in our test data
        List<Account> accounts = [select Id from Account limit 1];
        // there one account record
        System.assert(accounts.size() == 1);
        Account acc = accounts.get(0);
        List<Project__c> projects = [select Id from Project__c where Account__c = :acc.Id];
        // account has one project record
        System.assert(projects.size() == 1);
        List<Milestone__c> milestones = [select Id from Milestone__c where Project__c = :projects.get(0).Id];
        // project has 3 milestone records
        System.assert(milestones.size() == 3);
        List<Milestone_Task__c> milestoneTasks = [
            select Id from Milestone_Task__c 
            where Project__c = :projects.get(0).Id and Milestone__c = :milestones.get(0).Id
        ];
        // each milestone has 2 milestone task records
        System.assert(milestoneTasks.size() == 2);
    }
}